### ISSUE TITLE
Python module for wrangleCSV-NCDF.py missing.

### ISSUE THREAD

**Issue by neutvd** [KNMI/Hackathon-RDWD-DataSciencePlatform#1]
I think a python module failed to make it to the initial commit.

> bhw512 $ python wrangleCSV-NCDF.py
> Traceback (most recent call last):
>   File "wrangleCSV-NCDF.py", line 35, in <module>
>     import csvTooling as csvT
>   File "/net/bhw480/nobackup/users/neutvd/projects/hackathon-2017/Hackathon-RDWD-DataSciencePlatform/wrangler/csvTooling.py", line 16, in <module>
>     import jsonTooling as jst
>   File "/net/bhw480/nobackup/users/neutvd/projects/hackathon-2017/Hackathon-RDWD-DataSciencePlatform/wrangler/jsonTooling.py", line 7, in <module>
>     import jsonSyntaxTester as jsTstr
> ImportError: No module named jsonSyntaxTester
> 

Shouldn't there be a jsonSyntaxTester.py file somewhere?

**Comment by MikoKNMI** [comment]
solved
